language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

addons:
  postgresql: "9.3"

services:
    - mysql
    - postgresql

before_script:
    - composer self-update
    - composer install --no-ansi
    - mysql -e 'CREATE DATABASE dsql_test;'
    - mysql -e 'SET GLOBAL max_connections = 1000;'
    - psql -c 'CREATE DATABASE "atk4-dsql-test";' -U postgres
    - psql -c 'ALTER ROLE travis CONNECTION LIMIT -1;' -U postgres
    - mkdir -p build/logs

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then CM=""; NC=""; else CM=""; NC="--no-coverage"; fi
    - $CM ./vendor/bin/phpunit --configuration phpunit.xml $NC
    - $CM ./vendor/bin/phpunit --configuration phpunit-mysql.xml $NC
    - $CM ./vendor/bin/phpunit --configuration phpunit-pgsql.xml $NC

after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then
      echo "Merging coverage reports:";
      vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml;
      echo "We now have these coverage files:";
      ls -l build/logs;
      echo "Sending codeclimate report:";
      vendor/bin/test-reporter --coverage-report build/logs/cc.xml;
      echo "Sending codecov report:";
      TRAVIS_CMD="" bash <(curl -s https://codecov.io/bash) -f build/logs/cc.xml;
    fi

notifications:
    slack:
        rooms:
            - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
        on_success: change

    urls:
      - https://webhooks.gitter.im/e/b33a2db0c636f34bafa9

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

    email: false
